smsApp/urls.py
from django.urls import path
from . import views
from django.contrib import admin  



urlpatterns = [  
    # path('admin/', admin.site.urls),  
    path('',views.index),
    path('home',views.home),
    path('stu', views.stu), 
    path('addstudent',views.addstudent),
    path('studentpage',views.studentpage), 
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

studentManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('smsApp.urls'))
]

smsApp/models.py
from django.db import models

# Create your models here.

class Student(models.Model):  
    s_id = models.CharField(max_length=20)  
    s_name = models.CharField(max_length=100)
    s_lastname = models.CharField(max_length=100)
    s_street = models.CharField(max_length=100)
    s_city = models.CharField(max_length=100)
    s_district = models.CharField(max_length=100)
    s_state = models.CharField(max_length=100)
    s_pin = models.CharField(max_length=10)
    s_class = models.CharField(max_length=100)
    s_section = models.CharField(max_length=100)
    s_dob = models.DateField()
    s_gender = models.CharField(max_length=100)
    s_father_name = models.CharField(max_length=100)
    s_mother_name = models.CharField(max_length=100)
    s_fathers_occupation = models.CharField(max_length=100)
    s_fmobile_number = models.CharField(max_length=15)
    s_fathers_email = models.EmailField(max_length=100)
    s_password = models.CharField(max_length=25)  
    class Meta:  
        db_table = "Student" 
        
        

class Teacher(models.Model):  
    t_id = models.CharField(max_length=20)  
    t_name = models.CharField(max_length=100)
    t_lastname = models.CharField(max_length=100)
    t_street = models.CharField(max_length=100)
    t_district = models.CharField(max_length=100)
    t_state = models.CharField(max_length=100)
    t_pin = models.CharField(max_length=10)
    t_section = models.CharField(max_length=100)
    t_dob = models.DateField()
    t_gender = models.CharField(max_length=100)
    t_mobile = models.CharField(max_length=15)
    t_email = models.EmailField(max_length=100)
    t_adhar = models.CharField(max_length=100)
    t_doj = models.DateField(max_length=100)
    t_password = models.CharField(max_length=25)  
    class Meta:  
        db_table = "Teacher"

smsApp/forms.py
from django import forms  
from .models import Student  
from .models import Teacher

class StudentForm(forms.ModelForm):  
    class Meta:  
        model = Student  
        fields = "__all__"  
        
class TeacherForm(forms.ModelForm):  
    class Meta:  
        model = Teacher  
        fields = "__all__"         
    

smsApp/views.py
from django.shortcuts import render, redirect  
from .forms import StudentForm,TeacherForm 
from .models import Teacher,Student 

def index(request):
    return render(request,'index.html')

def home(request):
    return render(request,'index.html')
 
def studentpage(request):
    return render(request,'student.html')
 
def addstudent(request):
    return render(request,'indexsms.html')
     
def stu(request):  
    if request.method == "POST":  
        form = StudentForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = StudentForm()  
    return render(request,'indexsms.html',{'form':form})


# def stu(request):
#     obj=Student()
#     # obj.s_id=request.POST['s_id']
#     obj.s_name=request.POST['s_name']
#     obj.s_lastname=request.POST['s_lastname']
#     obj.s_street=request.POST['s_street']
#     obj.s_city=request.POST['s_city']
#     obj.s_district=request.POST['s_district']
#     obj.s_state=request.POST['s_state']
#     obj.s_pin=request.POST['s_pin']
#     obj.s_class=request.POST['s_class']
#     obj.s_section=request.POST['s_section']
#     obj.s_dob=request.POST['s_dob']
#     obj.s_gender=request.POST['s_gender']
#     obj.s_father_name=request.POST['s_father_name']
#     obj.s_mother_name=request.POST['s_mother_name']
#     obj.s_fathers_occupation=request.POST['s_fathers_occupation']
#     obj.s_fmobile_number=request.POST['s_fmobile_number']
#     obj.s_fathers_email=request.POST['s_fathers_email']
#     obj.s_password=request.POST['s_password']
#     obj.save()
#     return render (request,'indexsms.html',{'detail':'succesfully submit '})

def show(request):  
    students = Student.objects.all()  
    return render(request,"show.html",{'students':students})


def edit(request, id):  
    student = Student.objects.get(id=id)  
    return render(request,'edit.html', {'student':student}) 

def update(request, id):  
    student = Student.objects.get(id=id)  
    form = StudentForm(request.POST, instance = student)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'student':student})


def destroy(request, id):  
    student = Student.objects.get(id=id)  
    student.delete()  
    return redirect("/show")  

templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{student.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">student Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="s_id" id="id_s_id" required maxlength="20" value="{{ student.s_id }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">student Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="s_name" id="id_s_name" required maxlength="100" value="{{ student.s_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student street:</label>  
    <div class="col-sm-4">  
        <input type="email" name="s_street" id="id_s_street" required maxlength="254" value="{{student.s_street }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

templates/indexsms.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SMS</title>
</head>

<body>
    <!-- navigattion -->
    <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="home">Student Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Logout</a>
                </li>
            </ul>

        </div>
    </nav>
    <!-- nav-end -->

    <div align="center">
        <form method="POST" class="post-form" action="/stu">
            {% csrf_token %}

            <h3>Enter Details of student indexsms</h3>

            <label>Student Id:</label>
            <div class="col-sm-4">
                {{ form.s_id }}
            </div>
            <div>
                <label>student Name:</label>
                <div>
                    {{ form.s_name }}
                </div>
            </div>
            <div>
                <label>student LastName:</label>
                <div>
                    {{ form.s_lastname }}
                </div>
            </div>

            <div>
                <label>street:</label>
                <div>
                    {{ form.s_street }}
                </div>
            </div>

            <div>
                <label>city:</label>
                <div>
                    {{ form.s_city}}
                </div>
            </div>

            <div>
                <label>student city:</label>
                <div>
                    {{ form.s_district }}
                </div>
            </div>
            <div>
                <label>student state:</label>
                <div>
                    {{ form.s_state }}
                </div>
            </div>
            <div>
                <label>stuudet state:</label>
                <div>
                    {{ form.s_state }}
                </div>
            </div>
            <div>
                <label>student pincode:</label>
                <div>
                    {{ form.s_pin }}
                </div>
            </div>
            <div>
                <label>student class:</label>
                <div>
                    {{ form.s_class }}
                </div>
            </div>
            <div>
                <label>student section:</label>
                <div>
                    {{ form.s_section }}
                </div>
            </div>

            <div>
                <label>student Dob:</label>
                <div>
                    {{ form.s_dob }}
                </div>
            </div>

            <div>
                <label>student gender:</label>
                <div>
                    {{ form.s_gender }}
                </div>
            </div>
            <div>
                <label>student fathrs name:</label>
                <div>
                    {{ form.s_father_name }}
                </div>
            </div>

            <div>
                <label>student mother name:</label>
                <div>
                    {{ form.s_fathers_occupation }}
                </div>
            </div>
            <div>
                <label>student parents mobile:</label>
                <div>
                    {{ form.s_fmobile_number }}
                </div>
            </div>
            <div>
                <label>student email parents:</label>
                <div>
                    {{ form.s_fathers_email }}
                </div>
            </div>
            <button>Submit</button>
    </div>
    </div>
    </form>
    </div>

    <!-- footer start -->
    <footer class="container">
        <hr>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2017-2019 studentmanagementsystem@gmail.com <a href="#">Privacy</a> · <a href="#">Terms</a></p>
        <hr>
    </footer>
    <!-- footer end -->

</body>

</html>

templates/loginpage.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SMS</title>
</head>

<body>  <img src="/image/convo.jpg">
    <!-- services section start -->
    <section id="services">
      
        <div class="container mb-5 ">
            <h1 class="text-center text-capitalize pt-4">student Managemet system</h1>
            <hr class="mx-auto w-25 pt-4 ">
            

                 <div class="container">
                    <div class="row">
                        
                        <div class="col-lg-6 col-md-6 col-12">
                            <!-- contact us start -->
<section id="contact">
        <div class="container mb-5  ">
            <h1 class="text-center text-capitalize pt-4">Login</h1>
            <hr class="mx-auto w-25 pt-4 ">
            <div class="w-50 mx-auto">
                <form action="/action_page.php">
                    <div class="form-group">
                        <!-- <label for="email">Enter your Name:</label> -->
                        <input type="text" class="form-control" id="name" placeholder="username">
                    </div>
                    
                    <div class="form-group">
                        <!-- <label for="email">Email address:</label> -->
                        <input type="email" class="form-control" id="email" placeholder="email">
                    </div>
                    <div class="form-group">
                            <!-- <label for="password">password</label> -->
                            <input type="password" class="form-control" id="password" placeholder="password">
                        </div>
                        <button type="submit" class="btn btn-outline-primary">click here</button>
                </form>
    
            </div>
        </div>
    </section>
    <!-- contact us end -->
                    
                        </div>        
                    </div>
                </div>
            </div> 
    </section>
    <!-- service section end -->

    
 <!-- footer start -->
 <footer class="container">
    <hr>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2017-2019 studentmanagementsystem@gmail.com <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    <hr>  
</footer>
<!-- footer end -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>student Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th> ID</th>  
        <th> Name</th>
        <th>last Name</th>  
        <th> street</th>  
        <th> City</th>  
        <th>district</th>
        <th> state</th>  
        <th> pin</th>
        <th>class</th>  
        <th>section</th>  
        <th>dob</th>  
        <th>gender</th>
        <th>father name</th>  
        <th>mothr name</th>
        <th>father occupation</th>  
        <th> contact</th>  
        <th> email</th>  
         
    </tr>  
    </thead>  
    <tbody>  
{% for student in students %}  
    <tr>  
        <td>{{student.s_id }}</td>  
        <td>{{student.s_name }}</td>  
        <td>{{student.s_lastname  }}</td>  
        <td>{{student.s_street  }}</td>
        <td>{{student.s_city  }}</td>  
        <td>{{student.s_district }}</td>  
        <td>{{student.s_state  }}</td>  
        <td>{{student.s_pin  }}</td>
        <td>{{student.s_class  }}</td>  
        <td>{{student.s_section }}</td>  
        <td>{{student.s_dob  }}</td>  
        <td>{{student.s_gender  }}</td>
        <td>{{student.s_father_name  }}</td>  
        <td>{{student.s_mother_name }}</td>  
        <td>{{student.s_fathers_occupation  }}</td>  
        <td>{{student.s_fmobile_number  }}</td>
        <td>{{student.s_fmobile_email  }}</td>  
        <td>  
            <a href="/edit/{{ student.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ student.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/stu" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>

templates/student.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SMS</title>
</head>

<body>
    <!-- navigattion -->
    <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="home">Student Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Logout</a>
                </li>
            </ul>

        </div>
    </nav>
    <!-- nav-end -->


    <!-- services section start -->
    <section id="services">
        <div class="container mb-5 ">
            <h1 class="text-center text-capitalize pt-4">student details</h1>
            <hr class="mx-auto w-25 pt-4 ">
            
            <!-- <div class="row text-center">
                <div class="col-lg-3 col-md-3 col-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="images/add.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Add Student</h5>
                    
                            <a href="#" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="images/update.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Update Student</h5>
                            
                            <a href="#" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-3 col-12">
                    <div class="card" style="width: 21rem;">
                        <img class="card-img-top mt-5" src="images/view.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">view Student</h5>
                        
                            <a href="#" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="images/delete.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Delete Student</h5>
                            <a href="#" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
                 -->

                 <div class="container">
                    <div class="row">
                        <form method="POST" action="/addstudent">
                            {% csrf_token %}
                        <div class="col-lg-3 col-md-3 col-12">
                            <img src="{% static '/images/add.jpg' %}".jpg" class="bd-placeholder-img rounded-circle" width="140" height="140"/>
                            <h3>Add student</h3>
                            <p>To add new detail of any student</p>
                            <!-- <a class="btn btn-outline-primary" href="#" role="button">click here »</a> -->
                            <button type="submit" class="btn btn-outline-primary">click here</button>
                        </div>
                    </form>
                    

                        <div class="col-lg-3 col-md-3 col-12">
                            <img src="{% static '/images/view.jpg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140"
                                />       
                            <h3>View student</h3>
                            <p>To view all student</p>
                            <a class="btn btn-outline-primary" href="#" role="button">click here »</a></p>
                        </div>

                        <div class="col-lg-3 col-md-3 col-12">
                            <img src="{% static '/images/update.jpg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140"
                                />       
                            <h3>Update student</h3>
                            <p>To update the details of student</p>
                            <a class="btn btn-outline-primary" href="#" role="button">click here »</a></p>
                        </div>

                        <div class="col-lg-3 col-md-3 col-12">
                            <img src="{% static '/images/delete.jpg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140"
                                />       
                            <h3>Delete student</h3>
                            <p>Delete student records</p>
                            <a class="btn btn-outline-primary" href="#" role="button">click here »</a></p>
                        </div>
                    </div>
                </div>
            </div> 
    </section>
    <!-- service section end -->

    
<!-- contact us start -->
<section id="contact">
    <div class="container mb-5  ">
        <h1 class="text-center text-capitalize pt-4">Contact us</h1>
        <hr class="mx-auto w-25 pt-4 ">
        <div class="w-50 mx-auto">
            <form action="/action_page.php">
                <div class="form-group">
                    <label for="email">Enter your Name:</label>
                    <input type="text" class="form-control" id="name">
                </div>
                <div class="form-group">
                    <label for="email">Mobile Number:</label>
                    <input type="number" class="form-control" id="mobile">
                </div>
                <div class="form-group">
                    <label for="email">Email address:</label>
                    <input type="email" class="form-control" id="email">
                </div>

                <div class="form-group">
                    <label for="email">Message</label>
                    <textarea class="form-control"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Send</button>
            </form>

        </div>
    </div>
</section>
<!-- contact us end -->

 <!-- footer start -->
 <footer class="container">
    <hr>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2017-2019 studentmanagementsystem@gmail.com <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    <hr>  
</footer>
<!-- footer end -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>